FROM java:8-jre-alpine

RUN wget http://files.concurrentinc.com/driven/2.1/driven-server/driven-tomcat-2.1.4.zip
RUN unzip driven-tomcat-2.1.4.zip

CMD echo "See docs for more info. Install license, etc."

