---

- name: Wait for consul
  wait_for:
    host: "{{ consul_ip }}"
    port: "{{ consul_port }}"

- name: Run swarm manager
  docker: 
    ports:
      - "{{swarm_master_port}}:{{swarm_master_port}}"
    expose:
      - "{{swarm_master_port}}"
    restart_policy: always
    state: started
    image: swarm
    name: swarm-manager
    command: "manage -H :{{swarm_master_port}} --replication --advertise {{docker_host_ip }}:{{swarm_master_port}} consul://{{ consul_ip }}:{{ consul_port }}"
