---

- name: Wait for consul
  wait_for:
    host: "{{ consul_ip }}"
    port: "{{ consul_port }}"

- name: Run swarm manager
  docker: 
    ports:
      - "4000:4000"
    expose:
      - "4000"
    restart_policy: always
    state: started
    image: swarm
    name: swarm-manager
    command: "manage -H :4000 --replication --advertise {{docker_host_ip }}:4000 consul://{{ consul_ip }}:{{ consul_port }}"
