--- 

- name: Add user to docker group
  become: true
  user: 
    append: yes
    group: docker
    name: "{{ user }}"
  register: docker_user_set 

- name: Kill SSH
  shell: sleep 1; pkill -u {{ ansible_ssh_user }} sshd
  async: 3
  poll: 2
  when: docker_user_set | changed