---

- name: Install setuptools
  become: true
  yum:
    name: python-setuptools
    state: present

- name: Install pip
  become: true
  easy_install: 
      name: pip 

- name: Install docker-py
  become: true
  pip: 
      name: docker-py 
      state: present